services:
  crypto-pnl:
    build: .
    container_name: crypto-pnl

    restart: unless-stopped

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.crypto.rule=Host(`pnl.yourdomain.com`)"

      - "traefik.http.routers.crypto.entrypoints=websecure"

      - "traefik.http.routers.crypto.tls.certresolver=letsencrypt"

      - "traefik.http.services.crypto.loadbalancer.server.port=8501"

    networks:
      - traefik

networks:
  traefik:
    external: true